version: "3"

services:
  db_node_domain:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: PASSWORD
    container_name: wordpress_db

  wordpress:
    depends_on:
      - db_node_domain
    image: wordpress:latest
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: chamsocbabauhuonghuong.com
      WORDPRESS_DB_HOST: db_node_domain:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: PASSWORD
      LETSENCRYPT_HOST: chamsocbabauhuonghuong.com
      LETSENCRYPT_EMAIL: huuchi207@gmail.com
    container_name: wordpress

  wordpress_test2:
    depends_on:
      - db_node_domain
    image: wordpress:latest
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: mywilldomain.tk
      WORDPRESS_DB_HOST: db_node_domain:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: PASSWORD
      LETSENCRYPT_HOST: mywilldomain.tk
      LETSENCRYPT_EMAIL: huuchi207@gmail.com
    container_name: wordpress_test2  
volumes:
  db_data:

networks:
  default:
    external:
      name: nginx-proxy